### ISSUE TITLE
Mention color is always white

### ISSUE THREAD

**Issue by Leo40Git** [powercord-community/rolecolor-everywhere#23]
![image](https://user-images.githubusercontent.com/7997354/125345929-cf0cfd80-e361-11eb-9053-9e670358d456.png)
The colored role is the only role I had, and yet the mention color's still white...
This is after fully restarting Discord, by the way, so the cache shouldn't be affecting it.

**Comment by ben2224** [comment]
I had this problem as well. There was also no highlighting around the mention like usual, instead it looked like plain text.
(Although is no problem when the user has no coloured roles.)

**Comment by Leo40Git** [comment]
I added the highlighting around the mention myself. Without my CSS snippet it has no background, yeah.
