### ISSUE TITLE
Users with a top color don't get colored in mentions.

### ISSUE THREAD

**Issue by BruhDark** [powercord-community/rolecolor-everywhere#24]
If a user has a top role with a color that's not the default one, in a mention the color does not "render". It just makes it look like a failed mention, but when you click it, it mentioned the user. 

![](https://dark.hates-this.place/f/vlDjDg.png)
![](https://dark.hates-this.place/f/inA8lY.gif)

**Comment by cyyynthia** [comment]
Duplicate of #23
