### ISSUE TITLE
Coloring the account name in settings causes Discord to crash upon hovering over the settings icon

### ISSUE THREAD

**Issue by reoccurcat** [powercord-community/rolecolor-everywhere#31]
The only way I could find to fix this was to go to settings, clone it into the plugins, load missing plugins, go to rolecolor-everywhere's plugin settings, and turn off account name coloring. No crashing occurs after I do this.

**Comment by cyyynthia** [comment]
Cannot reproduce. This is probably caused by another plugin interfering with rolecolor-everywhere.
