### ISSUE TITLE
TypeError: originalType is not a function

### ISSUE THREAD

**Issue by Magi1053** [powercord-community/rolecolor-everywhere#6]
```
ed3a7dcc6b5123f1d0c8.js:16 TypeError: originalType is not a function
    at section.type (rolecolor-everywhere\index.js:148)
```

**Comment by redalpha01** [comment]
line 146 of index 
type function is now... nested inside type...
so going from 
const originalType = section.type;
to 
const originalType = section.type.type;

fixes this

**Comment by redalpha01** [comment]
I can't imagine that this is something that'll stay in canary though.
